[gitlab]
webhook_path = "/gitlab"
webhook_token = "Set $REVBOT_GITLAB__WEBHOOK_TOKEN env variable to specify securely"

[webex]
access_token = "Set $REVBOT_WEBEX__ACCESS_TOKEN environment variable to specify securely"
webhook_path = "/webex"
webhook_token = "Set $REVBOT_WEBEX__WEBHOOK_TOKEN env variable to specify securely"
